# Generated by Django 6.0.3 on 2026-05-06 11:31

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP')),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=225)),
                ('profile_pic', models.ImageField(upload_to='testimonial/')),
                ('bio', models.TextField()),
            ],
            options={
                'db_table': 'testimonial',
            },
        ),
        migrations.CreateModel(
            name='Momo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='menu/')),
                ('marked_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_percent', models.IntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cataagery_ho', to='main.category')),
            ],
            options={
                'db_table': 'momo',
            },
        ),
    ]
