# Generated by Django 6.0.3 on 2026-05-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=225)),
                ('profile_pic', models.ImageField(upload_to='testimonial/')),
                ('bio', models.TextField()),
            ],
            options={
                'db_table': 'testimonial',
            },
        ),
    ]
